######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 23 14:49:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
