sudo apt-get install git
sudo apt-get install vim
sudo apt-get install cat
sudo apt-get install pipe
sudo apt-get install ranger
sudo apt-get install gettext
sudo apt-get install python-numpy
sudo apt-get install python-scipy
sudo apt-get install python-pytils
sudo apt-get install python-opencv
sudo apt-get install python-pybrain
sudo apt-get install python-pygraphviz
sudo apt-get install python-opencl
sudo apt-get install python-django
sudo apt-get install python-mysqldb
sudo apt-get install python-pygame
sudo apt-get install python-pymad
sudo apt-get install python-pyaudio
sudo apt-get install python-simplecv
sudo apt-get install tig
sudo apt-get install awesome
sudo apt-get install wine
sudo apt-get install conky
