s apt-get install wine
s apt-get install cat
s apt-get install guake
s apt-get install pipe
s apt-get install gettext
s apt-get install python-numpy
s apt-get install python-scipy
s apt-get install python-pytils
s apt-get install python-opencv
s apt-get install python-pybrain
s apt-get install python-pygraphviz
s apt-get install python-opencl
s apt-get install python-django
s apt-get install python-mysqldb
s apt-get install python-pygame
s apt-get install python-pymad
s apt-get install python-pyaudio
s apt-get install python-simplecv
