######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 25 17:52:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
