######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 1 19:09:48 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
