######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 12:14:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BlockOperation.h FunctionOperation.h Operation.h ThreadPool.h
SOURCES += BlockOperation.cpp \
           FunctionOperation.cpp \
           main.cc \
           Operation.cpp \
           ThreadPool.cpp
