######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 23 14:39:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp main2.cpp stereo_slam.cpp
