######################################################################
# Automatically generated by qmake (3.0) ?? ??? 14 19:55:00 2013
######################################################################

TEMPLATE = app
TARGET = qtexp
INCLUDEPATH += .

# Input
SOURCES += main.cpp
